### ISSUE TITLE
Scrolling while loading with section headers leaves a gap

### ISSUE THREAD

**Issue by mjgaylord** [inspace-io/INSPullToRefresh#2]
First off, this is one of the best implementations I've seen of pull-to-refresh, very configurable and it works well. Great work. I am however experiencing what I think is a bug.

Basically, while refreshing a table view that uses section views, the pull-to-refresh view disappears when scrolling through the table. See my images below:

![screen shot 2015-02-25 at 3 01 12 pm](https://cloud.githubusercontent.com/assets/157073/6371097/eb30c49e-bd00-11e4-929f-9347bc41c992.png)

While loading I scroll through the table and the Pull-to-refresh view scrolls with the table while the section headers stop scrolling at the contentInset:

![screen shot 2015-02-25 at 3 01 25 pm](https://cloud.githubusercontent.com/assets/157073/6370990/64dddf04-bcff-11e4-9109-9aca3a816916.png)

Is there a way to pin the pull-to-refresh view to the top of the table, rather than have it scroll with the table? I think this is the simplest solution. The alternative is to alter the contentInset while scrolling which would ensure the section headers scroll all the way to the top of the table. If you could help me out, that would be great and I can go ahead and implement this component in the rest of the app.

**Comment by m1entus** [comment]
Thanks, i fixed this and also added scrollToTopAfterEndRefreshing which is default to YES.

**Comment by mjgaylord** [comment]
Brilliant, you rock!

**Comment by thomzon** [comment]
Hello,

I want to +1 the initial comment of mjgaylord, this implementation is really great.
Sadly, this bug is marked as resolved but I still experience it on my side. I am sure I have the right version, because the scrollToTopAfterEndRefreshing property is present.

I adapted the example code so that the list has a few sections, here is what it looks like after scrolling down a few pixels:
![ios simulator screen shot 13 jul 2015 11 24 23](https://cloud.githubusercontent.com/assets/697167/8646623/c3958ce0-2951-11e5-8a08-4371ee88e4e2.png)

Then if I scroll down enough, the section header suddenly snaps in the right place. This only happens with the first header.
![ios simulator screen shot 13 jul 2015 11 24 35](https://cloud.githubusercontent.com/assets/697167/8646630/d531f678-2951-11e5-9327-5ae68772c665.png)

**Comment by thomzon** [comment]
Thanks for the super fast merge of my fix.
Any chance a new pod version is scheduled soon with this fix included ?

**Comment by m1entus** [comment]
Done, 1.0.10 is on pods
